name: afrosync
description: "AfroSync bitches"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  video_player: ^2.10.0
  go_router: ^16.2.1
  audio_metadata_reader: ^1.4.2
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  file_picker: ^10.3.3

  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/music/

  fonts:
    - family: FormaDJR
      fonts:
        - asset: assets/fonts/FormaDJR-Light.ttf
          weight: 300
        - asset: assets/fonts/FormaDJR-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/FormaDJR-Regular.ttf
          weight: 400
        - asset: assets/fonts/FormaDJR-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/FormaDJR-Medium.ttf
          weight: 500
        - asset: assets/fonts/FormaDJR-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/FormaDJR-Bold.ttf
          weight: 700
        - asset: assets/fonts/FormaDJR-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/FormaDJR-Black.ttf
          weight: 900
        - asset: assets/fonts/FormaDJR-BlackItalic.ttf
          weight: 900
          style: italic
